### ISSUE TITLE
ArgumentParser<T>.Parse() prints all arguments

### ISSUE THREAD

**Issue by EaranMaleasi** [codeaddicts/libArgument#2]
`ArgumentParser<T>.Parse()` always prints all arguments which should be optional if not even be completely discarded. On top of that, it prints those arguments in a somewhat random order.

**Comment by NikxDa** [comment]
The corresponding line has been updated to be a comment. See [here](https://github.com/codeaddicts/libArgument/blob/master/src/libArgument/libArgument/ArgumentParser.cs#L126).
